# Generated by Django 5.0.3 on 2024-03-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(blank=True, db_column='nombreCategoria', max_length=100, null=True)),
                ('descripcion_categoria', models.TextField(blank=True, db_column='descripcionCategoria', null=True)),
            ],
            options={
                'db_table': 'categoriaproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimientoInventario',
            fields=[
                ('id_detalle_movimiento', models.AutoField(db_column='idDetalleMovimiento', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detallemovimientoinventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id_detalle_orden_compra', models.AutoField(db_column='idDetalleOrdenCompra', primary_key=True, serialize=False)),
                ('cantidad_comprada', models.IntegerField(blank=True, db_column='cantidadComprada', null=True)),
                ('valor_unitario', models.DecimalField(blank=True, db_column='valorUnitario', decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, db_column='valorTotal', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'detalleordencompra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.AutoField(db_column='idDetalleVenta', primary_key=True, serialize=False)),
                ('cantidad_vendida', models.IntegerField(blank=True, db_column='cantidadVendida', null=True)),
                ('valor_unitario', models.DecimalField(blank=True, db_column='valorUnitario', decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, db_column='valorTotal', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'detalleventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.AutoField(db_column='idMovimiento', primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(blank=True, db_column='tipoMovimiento', max_length=50, null=True)),
                ('fecha_movimiento', models.DateTimeField(db_column='fechaMovimiento')),
            ],
            options={
                'db_table': 'movimientoinventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden_compra', models.AutoField(db_column='idOrdenCompra', primary_key=True, serialize=False)),
                ('fecha_orden_compra', models.DateField(blank=True, db_column='fechaOrdenCompra', null=True)),
                ('valor_total_orden_compra', models.DecimalField(db_column='valorTotalOrdenCompra', decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'ordencompra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, db_column='nombreProducto', max_length=100, null=True)),
                ('descripcion_producto', models.TextField(blank=True, db_column='descripcionProducto', null=True)),
                ('precio_producto', models.DecimalField(blank=True, db_column='precioProducto', decimal_places=2, max_digits=10, null=True)),
                ('cantidad_producto', models.IntegerField(blank=True, db_column='cantidadProducto', null=True)),
                ('imagen_producto', models.ImageField(blank=True, db_column='imagenProducto', null=True, upload_to='productos/')),
                ('estado_producto', models.CharField(blank=True, db_column='estadoProducto', max_length=250, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(db_column='idProveedor', primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(blank=True, db_column='nombreProveedor', max_length=50, null=True)),
                ('correo_electronico', models.CharField(blank=True, db_column='correoElectronico', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad_productos_pedido', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, db_column='rolNombre', max_length=50, null=True)),
                ('descripcion_rol', models.TextField(blank=True, db_column='descripcionRol', null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(blank=True, db_column='primerNombre', max_length=100, null=True)),
                ('primer_apellido', models.CharField(blank=True, db_column='primerApellido', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('correo_electronico', models.CharField(blank=True, db_column='correoElectronico', max_length=100, null=True)),
                ('contrasena_usuario', models.CharField(blank=True, db_column='contrasenaUsuario', max_length=50, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(db_column='idVenta', primary_key=True, serialize=False)),
                ('tipo_venta', models.CharField(blank=True, choices=[('Vendedor', 'Vendedor'), ('Cliente', 'Cliente')], db_column='tipoVenta', max_length=50, null=True)),
                ('fecha_venta', models.DateField(blank=True, db_column='fechaVenta', null=True)),
                ('valor_total_venta', models.DecimalField(blank=True, db_column='valorTotalVenta', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
    ]
